travis:
  secure:
    BINSTAR_TOKEN: SdsRcr8nudO9bXwsOUxauW3lZU+4yzLG26SrEq6LwNEdf+Fg8heh0Q7lz55aFNDhuuNssfMmFBu6MI9D5eRpKmhlQUnv5w+17IuYaF5YpnEKYnyLroWz2mlfVzbUf2bqSEAfzk2ojwmZ/zMPatclWUlxk2Ip86dhJZeKCWnyCxlnyzY3ekoR754gktPIOBAMO+Wvo8U7747kjL3UCS+q3kVck3vfys9IOHVieDbEnVcxhsuNmP+JCVSwDWaO0eLvUiJhtyqPIprAafbegwJjgusCP2hi90XtSglcXNBvHVGezDkhpHKEOi5Jo39PLQMonHM3NbMoNA/59O7WBvthTeccZCA5NRpz2ZIrBp6HZCfrs9kU+xzmFZ/rkZQc8OyYltRA+8b+vClw3+QDhhzPZ9EhTzyH+mjCBW9TL81IA/IOxeK81pot2cNTgairZSYgqidSAxoz4FYHPVKHDVSRZ2z8IRsKXfdHAbSzpT+El4QVKrcRsDAplMtC8rYXfjftXXDzF0IDTweiroQ9r7q0QGky4k15/G+nYBMW9t1vcnC1ZyxfzrHDm1jLafMuRLArGBTxgqUPkC8v4iMQKeN2yaJM5/nKaIQ5DvyaaDWyyxXcwCleEnMpJGC9nwczAw9XYQS59O4YVd/Mf0HCOGKH9CBL9/4hQ1uuA93VYp/8b9E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
